//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


namespace AFH_Scheduler.Database
{    
    public partial class HomeInspectionEntities : DbContext
    {
        public HomeInspectionEntities()
            : base("name=HomeInspectionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Home_History> Home_History { get; set; }
        public virtual DbSet<Inspection_Outcome> Inspection_Outcome { get; set; }
        public virtual DbSet<Provider_Homes> Provider_Homes { get; set; }
        public virtual DbSet<Provider> Providers { get; set; }
        public virtual DbSet<Scheduled_Inspections> Scheduled_Inspections { get; set; }
    }
}
