//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFH_Scheduler.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspection_Outcome
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inspection_Outcome()
        {
            this.Home_History = new HashSet<Home_History>();
        }
    
        public string IOutcome_Code { get; set; }
        public string IOutcome_Mintime { get; set; }
        public string IOutcome_Maxtime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Home_History> Home_History { get; set; }
    }
}
