
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AFH_Scheduler.Database
{

using System;
    using System.Collections.Generic;
    
public partial class Provider
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Provider()
    {

        this.Provider_Homes = new HashSet<Provider_Homes>();

    }


    public long Provider_ID { get; set; }

    public string Provider_Name { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Provider_Homes> Provider_Homes { get; set; }

}

}
